name: Upload and Download Artifacts

on: 
  push:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload README.md
        uses: actions/upload-artifact@v4
        with:
          name: readme-artifact
          path: README.md

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download README.md
        uses: actions/download-artifact@v4
        with:
          name: readme-artifact
          path: .